name: worth-platform

version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: apps/api/Dockerfile
    container_name: api
    restart: always
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://user:password@auth-db:5432/db
      - JWT_SECRET=supersecretkey
      - NODE_ENV=production
    ports:
      - "3346:3346"
    networks:
      - app-network

  ### 🗄 Database per Auth ###
  db:
    image: postgres:15
    container_name: db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5433:5432"
    networks:
      - app-network
    volumes:
      - db_data:/var/lib/postgresql/data

networks:
  app-network:

volumes:
  db_data:
